development:
  adapter: sqlite3
  database: db/tarot_development.db
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/tarot_test.db
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/tarot_production.db
  pool: 5
  timeout: 5000